name: Release

on:
  push:
    tags:
      - 'v*'
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Run tests
        run: go test -v ./test

      - name: Build
        run: |
          GOOS=windows GOARCH=amd64 go build -o bin/gojidb-windows-amd64.exe .
          GOOS=linux GOARCH=amd64 go build -o bin/gojidb-linux-amd64 .
          GOOS=darwin GOARCH=amd64 go build -o bin/gojidb-darwin-amd64 .
          GOOS=darwin GOARCH=arm64 go build -o bin/gojidb-darwin-arm64 .

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: bin/*
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}